language: java
jdk: oraclejdk8

before_install:
  - chmod +x mvnw

sudo: required

notifications:
  email:
    recipients:
      - revathiieee@gmail.com
    on_success: never
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
